apiVersion: shrine/v1
kind: Team
metadata:
  name: ops_docs
spec:
  displayName: "DevOps Documentation"
  contact: "carlos.kas21@gmail.com"
  quotas:
    maxApps: 3
    maxResources: 10
  registryUser: legion
